spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ch4-payments-system

  datasource:
    url: ${DB_URL:jdbc:h2:mem:ch4_payments_system;MODE=MySQL;DATABASE_TO_LOWER=TRUE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    defer-datasource-initialization: true  # 테이블 먼저 만들고 data.sql 돌려야함
  sql:
    init:
      mode: always  # data.sql 항상 실행 되게하는 것

jwt:
  secret-key: fhrmdlsrlsmddldjqtdmausqnsaudzhemwkrtjddldksehlfxjdlsepdjejgrpwkrtjdgktutwygkgktkffuwntpdy
  expiration-time: 3600000

portone:
  base-url: ${PORTONE_BASE_URL:https://api.portone.io}
  api-secret: ${PORTONE_API_SECRET:}
  store-id: ${PORTONE_STORE_ID:}
  channel-key: ${PORTONE_CHANNEL_KEY:}
  webhook-secret: ${PORTONE_WEBHOOK_SECRET:}
